---
title: "Coronavirus Google Trends Tracker"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard); library(gtrendsR); library(plotly); library(dplyr)
```

Inputs {.sidebar}
-------------------------------------

_DISCLAIMER: This was created as part of a class project and should not be used as official health information._

Use this app to see how popular the search term **coronavirus** has been over time and what related queries are being searched for on Google. Use the options below to compare the performance to another search term, change the time frame, or change source of the data.

Data is sourced from Google and retrieved through the gtrendsR package. Information last updated March 21, 2020.

```{r}

# see coronavirus search alone or compare to another query
radioButtons("view", h2("See interest over time for 'coronavirus'..."),
                       c("by itself" = "1",
                         "compared to: " = "2"),
                 selected = "2")
textInput("search", NULL, value = "virus")

selectInput("time", "Show results from the: ",
                c("Past hour" = "now 1-H",
                  "Past day"= "now 1-d",
                  "Past 7 days" = "now 7-d",
                  "Past 30 days" = "today 1-m",
                  "Past 90 days" = "today 3-m",
                  "Past 12 months" = "today 12-m",
                  "Past 5 years" = "today+5-y"
                  ), selected = "now 1-d")

selectInput("source", "Source results from: ",
            c("All web" = "web",
              "YouTube only" = "youtube",
              "Images only" = "images",
              "Froogle only" = "froogle"
            ))

```
(Graphics may take a few moments to load, please be patient!)

Row
-----------------------------------------------------------------------

### Search hits plotted on a relative scale

```{r comparison}

renderPlotly({
  if (input$view == 2) {
    y = gtrends(c("coronavirus", input$search), time = input$time, gprop = input$source) 
  } else {
    y = gtrends("coronavirus", time = input$time, gprop = input$source)
  }
  
  plot(y)
})

```

Row
-----------------------------------------------------------------------

### Related queries for 'coronavirus'

```{r related queries}
# Related queries
renderPlotly({
  x = gtrends("coronavirus", time = input$time, gprop = input$source)
  
  if (is.null(x$related_queries)) {
    verbatimTextOutput("No results found, try a different search!")
  } else {
    
    queries = x$related_queries %>% filter(subject >= 1)
    queries$subject = as.numeric(queries$subject) # make number
    queries = na.omit(queries)
    
    queries$value <- factor(queries$value, levels = unique(queries$value)[order(queries$subject, decreasing = FALSE)]) # order
    
    x <- list(title = "Search hits")
    y <- list(title = "Related query")
    fig = plot_ly(queries, x = ~subject, y = ~value, type = 'bar', name = "Related queries", marker = list(color = '#9119b8')) 
    fig = fig %>% layout(xaxis = x, yaxis = y)
    
    fig
  }
  
    
})

```

