---
title: "Question 4: Kirby21 Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Select data

```{r select data}

# User selects type (1-3) and level (1-5)
selectInput("type", "Type:",
                c("1" = "1",
                  "2" = "2"))

selectInput("level", "Level:",
                c("1" = "1",
                  "2" = "2",
                  "3" = "3"))

# radioButtons("type", "Choose type:",
#                c("Type 1" = "1",
#                  "Type 2" = "2"))
# 
# radioButtons("level", "Choose level:",
#                c("Level 1" = "1",
#                  "Level 2" = "2",
#                  "Level 3" = "3"))

h4("Chosen type:")
#verbatimTextOutput("otype")
renderText({input$type})


h4("Chosen level:")
#verbatimTextOutput("olevel")
renderText({input$level})
```

Column {data-width=600}
-----------------------------------------------------------------------

### Plot of Average Composition

```{r display composition}

# Read in chosen Kirby data
library(magrittr); library(dplyr); library(MRIcloudT1volumetrics); library(ggplot2)
## Change this to where the data directory is
dat = readSubject("/Users/gracewindheim/Documents/gmwDataSci/hw4temp/kirby_3_1_ax_283Labels_M2_corrected_stats.txt")
dat = subject2df(dat)

#### CREATE PLOT ####

#t = reactive({as.numeric(input$type)})
#l = reactive({as.numeric(input$level)})

#x = reactive({filter(dat, type == input$type, level == input$level)})
#x = data.frame(x)

# tl = reactive({
#   filter(dat, type == t(), level == l())
#   })


#plotOutput("plot1")
renderPlot({
  dat %>% filter(type == input$type, level == input$level) %>% ggplot(aes(x=roi, y=volume)) + geom_col()
})


# Find the composition

# Make plotly of the composition
library(plotly)


```

### Chart C

```{r}
#plotlyOutput("compPlot")

library(plotly)

renderPlotly({
  fig = plot_ly(
  x = c("giraffes", "orangutans", "monkeys"),
  y = c(20, 14, 23),
  name = "SF Zoo",
  type = 'bar')
  })
```

