---
title: "Shiny App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard); library(tidyverse); library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
orig = read.csv("listingsrefined.csv", header=T)

airpre = select(orig, price, room_type, bathrooms, bedrooms, reviews_per_month, accommodates, host_is_superhost)

air = na.omit(airpre)

plot_ly(data = air, x = ~bedrooms, y = ~price, color = ~room_type) 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
# Create Training and Test data -
set.seed(100)  # setting seed to reproduce results of random sampling
trainingRowIndex <- sample(1:nrow(air), 0.8*nrow(air))  # row indices for training data
trainingData <- air[trainingRowIndex, ]  # model training data
testData  <- air[-trainingRowIndex, ]   # test data

lmMod <- glm(price ~ host_is_superhost + room_type + bathrooms + bedrooms + accommodates + reviews_per_month, data=trainingData)  # build the model

pricePred <- predict(lmMod, testData)  # predict price
#summary(lmMod)

actuals_preds <- data.frame(cbind(actuals = testData$price, predicteds = pricePred))  # make actuals_predicteds dataframe.
correlation_accuracy <- cor(actuals_preds)  # 67.6%
head(actuals_preds)
```

### Chart C

```{r}
# user input example
host_is_superhost = 'f'
room_type = "Private room"
bathrooms = 1
bedrooms = 1
accommodates = 2
reviews_per_month = 6

userInput = data.frame(host_is_superhost, room_type, bathrooms, bedrooms, accommodates, reviews_per_month)

userPred = predict(lmMod, userInput)
userPred

# actual vs. predicted y graph
finalPlot = plot_ly(data = actuals_preds, x = ~actuals, y = ~predicteds)


hline <- function(y = 0, color = "blue") {
  list(
    type = "line", 
    x0 = 0, 
    x1 = 1, 
    xref = "paper",
    y0 = y, 
    y1 = y, 
    line = list(color = color)
  )
}

# add prediction from user input
finalPlot %>% layout(shapes = list(hline(userPred)))
```

